import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Task_Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='bg-slate-200'>
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
