import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import PageLoader from "./components/PageLoader";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Task_Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${rubik.className} min-h-screen text-slate-100`}>
        <PageLoader />
        <Navbar />
        <main className='min-h-[calc(100vh-80px)] pb-12'>{children}</main>
      </body>
    </html>
  );
}
